set relativenumber
set number
set nowrap
syntax on
filetype indent on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set scrolloff=5
let g:UltiSnipsExpandTrigger="<F4>"


" nerdtree settings if you want to enable them
let NERDTreeShowHidden=1
autocmd VimEnter * NERDTree | set number |set relativenumber| wincmd l | wincmd l
colorscheme gruvbox
set background=dark
"
vsplit
terminal zsh
