#!/bin/bash

# this file is meant to be sourced, and then you have many functions with
# which to install arch

# this installs grub on /mnt/boot
function kdeFixApplicationLauncher {
	pacInstall neovim
	nvim /home/$USER/.config/kglobalshortcutsrc
}

echo " "
echo "kdeFixApplicationLauncher --> opens nvim to shortcuts"
echo "ensure to change the kde launcher shortcut to alt-F1"
echo "https://forum.manjaro.org/t/add-custom-keyboard-shortcuts-from-terminal/58654"
echo "ensure to look for Application Launcher in nvim"
echo " "

function fixTouchpadTapToClick {
	su -c "touch /etc/X11/xorg.conf.d/40-libinput.conf"
	su -c "bat ./40-libinput.conf >> /etc/X11/xorg.conf.d/40-libinput.conf"
}

echo " "
echo "fixTouchpadTapToClick --> fixes issue where \n
tap to click may not work well"
echo "The command basically takes a 40-libinput.conf file \n
in the current directory and adds it to the proper directory\n
for xorg"
echo "requires root password, and bat \n
and also, libinput synaptics drivers etc."

echo "https://www.reddit.com/r/archlinux/comments/v1sdem/touchpad_tap_to_click_doesnt_work/"
echo " "

function obsStudioIntelWorkaround {
	sudo pacman -Rcs xf86-video-intel
	#https://www.reddit.com/r/artixlinux/comments/sq2qqh/obs_studio_screen_keeps_flickering_ive_tried/
}

echo "obsStudioIntelWorkaround --> uninstalls xf86-video-intel"
echo "I've tested that this doesn't cause crashes"
echo "and i can play some games using protonDB"
echo " "

function pacInstall {
	sudo pacman -S $@ --needed --noconfirm
}


echo "pacInstall [packages] --> executes sudo pacman -S --needed --noconfirm"

